### ISSUE TITLE
ghcp command not found with `working-directory`

### ISSUE THREAD

**Issue by itkq** [aquaproj/update-checksum-action#47]
Related: https://github.com/aquaproj/update-checksum-workflow/pull/60

Example:
- https://github.com/itkq/dotfiles/blob/5a755656836f998438c0caa6a647f9b6ee82c932/.github/workflows/update-aqua-checksums.yml
- https://github.com/itkq/dotfiles/actions/runs/10161966163/job/28101620572

aqua-installer run in `working-directory` and created a symbolic link to `ghcp`, but got `ghcp` command not found error.  I guess because the following process executes in the root directory?
https://github.com/aquaproj/update-checksum-action/blob/e6cea01abbad3bc40ff6b3dd2b7e6f7011cf53e6/action.yaml#L56-L84

**Comment by suzuki-shunsuke** [comment]
Thank you for your report!
I'll take a look.

**Comment by suzuki-shunsuke** [comment]
I'm working on fixing this.
The workaround is to add aqua.yaml on the repository root directory and manage ghcp in it.

**Comment by itkq** [comment]
Thanks! Workaround 1 worked fine. I guess this way is good enough because ghcp is not required other than update-checksum-workflow in my use case. This issue can be closed.

**Comment by suzuki-shunsuke** [comment]
Thank you. Looks good. I close this issue.
